### ISSUE TITLE
Nice job! and sir can you please release the naive code of predicting the instance segmentation results and flow results?

### ISSUE THREAD

**Issue by linshideng** [zkawfanx/StableLLVE#5]
Nice job! 
and sir can you please release the naive code of predicting the instance segmentation results and flow results?
it will help a lot!

**Comment by zkawfanx** [comment]
Sorry for the late reply, lol. I may release these codes in about two weeks.

**Comment by yejing0** [comment]
> Looking forward to releasing these codes



> Sorry for the late reply, lol. I may release these codes in about two weeks.

**Comment by zkawfanx** [comment]
The prediction codes for instance segmentation and optical flow are updated in the **_etc_** folder. You can check it out.

**Comment by yejing0** [comment]
Thank you for your reminder. If I run into any other problems, I'll ask you again for advice.


| |
yejing_013
|
|
***@***.***
|
On 9/2/2022 ***@***.***> wrote：

The prediction codes for instance segmentation and optical flow are updated in the etc folder. You can check it out.
