### ISSUE TITLE
Can't load the checkpoint.pth

### ISSUE THREAD

**Issue by 69DaMaoMi** [zkawfanx/StableLLVE#6]
Hello, I can't load the checkpoint.pth while testing some images.
Does the pretrained model work?

Thanks a million.

**Comment by zkawfanx** [comment]
It is OK for me to load the pretrained model. Do you run test.py in the rootdir of the project. Maybe you can show me the specific outputs of the error when you ran the test code and I can find out the problem.

**Comment by 69DaMaoMi** [comment]
Thanks for replying.
The weird thing is that it doesn't output any error.
The unet is successfully built but the next command which is loading pretrained run infinitely, and can't even use ctrl+z to terminate.
FYI, I'm using Windows' anaconda to run this project.

**Comment by zkawfanx** [comment]
I may see the problem. What version of Pytorch is used by you? I met the problem when I used Pytorch with latest version. You may try an older version and see if it can help.

**Comment by 69DaMaoMi** [comment]
It finally works!!!
I'm now using wsl2 under windows 11 with torch==1.5.0 and cuda=10.2.
Thank you for your hard work and reply.
